### ISSUE TITLE
backtick substitution fail for fish shell

### ISSUE THREAD

**Issue by teeann** [johannes-mueller/dired-gitignore.el#8]
First, thank you for this helpful Emacs package!
Currently, the backtick substitution in `dired-gitignore--files-to-be-ignored` does not work for **Fish** shell.
My suggestion is to replace ```git check-ignore `ls -A1` ``` with `git check-ignore *` instead.

**Comment by johannes-mueller** [comment]
Thanks for reporting this, @teeann. Unfortunately your proposal using `*` does not work as it wouldn't affect the dotfiles. That is the reason why I am using `ls -A1` in the first place. 

However, the `$(ls -A1)` notation seems to work in fish. 

Please reopen if it still does not work.

**Comment by johannes-mueller** [comment]
Well, as it turns out the `$(...)` notation was introduced in fish not before version 3.4.0. All the solutions I could think of making it work for older versions of fish would require to make things riskily complex. So I would prefer not to support fish < 3.4.0.
